### ISSUE TITLE
Automatically tag new ColumnTypes

### ISSUE THREAD

**Issue by n3o77** [unlooped/unlooped-grid-bundle#147]
When creating a new ColumnType in a project it needs to be tagged in a service configuration. 

i.E.:
```yaml
    App\ColumnType\:
        resource: '../src/ColumnType/*'
        tags: ['unlooped_grid.column']
```

It would be nice if all classes which extend the `AbstractColumnType` would be automatically considered without the configuration need.

**Comment by core23** [comment]
Must be done for each project:

```yaml

services:
    _instanceof:
        Unlooped\GridBundle\ColumnType\ColumnTypeInterface:
            tags: ['unlooped_grid.column']
    _instanceof:
        Unlooped\GridBundle\FilterType\FilterType:
            tags: ['unlooped_grid.filter']
```

It is not possible to add this configuration to the bundle itself, because of symfony service loading / registration.
